from enum import Enum

class LogEvent(Enum):
    THREAD_STARTED = "THREAD_STARTED",
    THREAD_ENDED = "THREAD_ENDED",
    CONFIG_LOADER_STARTER = "CONFIG_LOADER_STARTER",
    COLLECTING_METRICS_STARTED = "COLLECTING_METRICS_STARTED",
    DETECTING_ISSUES_STARTED = "DETECTING_ISSUES_STARTED",
    RELIABILITY_AGENT_STARTED = "RELIABILITY_AGENT_STARTED",
    SCHEDULER_SIGNAL_RECEIVED = "SCHEDULER_SIGNAL_RECEIVED",
    HANDLE_SHUTDOWN_SIGNAL_RECEIVED = "HANDLE_SHUTDOWN_SIGNAL_RECEIVED",
    TICK_COMPLETED = "TICK_COMPLETED",
    TICK_DURATION = "TICK_DURATION",
    INTERVAL_SECONDS = "INTERVAL_SECONDS"
